server:
  port: 4100

spring:
  application:
    name: sct-admin-biz

  profiles:
    active: dev
  cloud:
    config:
      name: ${spring.application.name}
      profile: ${spring.profiles.active}

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://sct-auth:4000/oauth/token
      user-authorization-uri: http://sct-auth:4000/oauth/authorize
    resource:
      token-info-uri: http://sct-auth:4000/oauth/check_token

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://sct-eureka:8761/eureka/

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: cn.tycoding.api.admin.api.entity

#mybaatis分页插件pagehelper设置
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true

# 打印sql
logging:
  level:
    cn.tycoding.api.admin.biz.mapper: DEBUG
