server:
  port: 8888

spring:
  application:
    name: template-config
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:9004

  # 获取本地配置文件，本身支持：本地储存、git远程、SVN
  profiles:
    active: native

  cloud:
    config:
      server:
        # 获取本地配置文件的位置
        native:
          search-locations: classpath:config/

eureka:
  client:
    service-url:
      # Eureka注册中心连接地址
      # 如果注册中心地址配置的域名，这里使用 http://域名/eureka/ 格式
      defaultZone: http://localhost:8080/eureka/
